### ISSUE TITLE
Security Issues

### ISSUE THREAD

**Issue by jon-steele** [vociapp/voci#6]
All inputs of every form should be getting validated and handled to prevent xss, sql injection, or other vulnerabilities

**Comment by jon-steele** [comment]
Login security needs to be better

- Passwords can be brute forced, as there is no limit to guesses. Must implement
- Implement two factor authentication. Phones & email can be used for verification. There are apis online that can do this for us, or we can send emails directly from our site.

**Comment by brezden** [comment]
Password criteria should be created

- Password Length (8+)
- Upper case and lower
- Special Character

Alongside this we should have error handling for showing the user what they are specifically missing in the password they tried to make.

**Comment by jon-steele** [comment]
Security updated.
